export const OPENROUTER_TEXT_TIMEOUT_MS = 30_000
export const OPENROUTER_IMAGE_TIMEOUT_MS = 60_000
export const OPENROUTER_TEXT_MAX_TOKENS = 2_000
export const OPENROUTER_POSTER_TEXT_MAX_TOKENS = 400
export const OPENROUTER_IMAGE_MAX_TOKENS = 2_048
